#kubectl api-resources
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:13.16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: ecommerce
        - name: POSTGRES_PASSWORD
          value: Pg1234
        - name: POSTGRES_DB
          value: ecommerce

---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: fakeshop
spec:
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
      - name: fakeshop
        image: benattee/fakeshop-test:v1
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgre
        - name: DB_USER
          value: ecommerce
        - name: DB_PASSWORD
          value: Pg1234
        - name: DB_NAME
          value: ecommerce
---
apiVersion: v1
kind: NodePort
metadata:
  name: fakeshop
spec:
  selector:
    app: fakeshop
  ports:
  - port: 5000